# Generated by Django 3.0.1 on 2019-12-25 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=128, verbose_name='订单编号')),
                ('start_palce', models.CharField(default='', max_length=500, verbose_name='出发地')),
                ('end_place', models.CharField(default='', max_length=500, verbose_name='目的地')),
                ('start_time', models.DateTimeField(verbose_name='行程开始时间')),
                ('end_time', models.DateTimeField(verbose_name='行程结束时间')),
                ('status', models.IntegerField(choices=[(0, '未派单'), (1, '行程中'), (2, '行程结束')], default=0, verbose_name='状态')),
                ('order_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='行程单用户')),
            ],
        ),
    ]
